# Generated by Django 4.2.30 on 2026-06-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
