# Generated by Django 4.2.30 on 2026-06-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_alter_despesa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='observacao',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
        ),
    ]
